<div class="card my-4" >
        <div class="card-body">
            <div class="container">
                <div class="row">

                    <div class="col-md-2" style="padding-left:0">
                        <img class="img-fluid rounded " src="Img/LoremImg.jpg">
                    </div>
                    <div class="col-md-6">
                        <h3></h3>
                        <h6 class="card-subtitle mb-2 pt-1"><span class="badge bg-dark">Album</span></h6>
                        <h5 class="card-subtitle mb-2 text-muted pt-5">Song1, Song2, Sonng3 ...</h6>
                    </div>
                    <div class="col-md-4">
                        <h4 class="pt-5">Average rating</h4>
                        
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                      </p>
                    </div>
                </div>
            </div>
        </div>
    </div>