<div class="col-sm-2 my-2" >
    <div class="card clickable" onClick="location.href='<?php echo "band.php?band=".$find_var["bid"] ?>'">
      <div class="card-body ">
          <img class=" rounded-circle img-fluid mb-4"  src="<?php echo returnBandimgPath($find_var["photo"]) ?>">
        <h5 class="card-title tritecky "><?php echo $find_var["bnm"] ?></h5>
        <h6 class="card-subtitle mb-1 pt-1"><span class="badge bg-dark">Artist</span></h6>
      </div>
    </div>
  </div>