<div class="album card my-4" onClick="location.href='album.php?album=<?php echo $row_alb["id"]?>'">
        <div class="card-body">
            <div class="container">
                <div class="row">

                    <div  class="col-md-2" style="padding-left:0">
                        <img class="img-fluid rounded " src="Img/LoremImg.jpg">
                    </div>
                    <div class="col-md-6">
                        <h3><?php echo $row_alb["name"]?></h3>
                        <h6 class="card-subtitle mb-1 pt-1"><span class="badge bg-dark">
                            <?php echo $row_alb["single"]==0? "Album":"Single";?>
                        </span></h6>
                        <h5 class="card-subtitle mb-2 text-muted pt-5">
                            <?php  
                            $songs = GetRandomSongs($db,$row_alb["id"]);
                            for($i = 0; $i <= 2; $i++){
                                echo $songs[$i][0];
                                if ($i <2){
                                    echo ", ";
                                }else{
                                    echo " ...";
                                }
                            }
                            ?>
                        </h5>
                    </div>
                    <div class="col-md-4">
                        <h4 class="pt-5">Average rating</h4>
                        
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                       <img src ="Img/star.svg">
                      
                    </div>
                </div>
            </div>
        </div>
    </div>