<?php
$title = "Rater - ".$row["albname"];
require("./view/head.phtml");
require("./phpFunc/utils.php")

?>
<style>
  .band-container{
    background: linear-gradient(hsla(<?php echo getColorFromID($row["albid"])?>, 77%, 51%, 0.525), #00000000); 
}
.tritecky {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
</style>
<div class="band-container">
    <div class="container pt-5 ">

        <h1 class="display-2" style="font-weight: bold; padding-top:10%"><?php echo $row["albname"] ?></h1>
        <div class="text-muted">
            <h5><a href="<?php echo "band.php?band=".$row["bndid"] ?>"><?php echo $row["name"]. "</a> • ". $row["yr"]." • " . $row["songCnt"] ." SONGS • ". round($row["lenght"] /60)." min"?> </h5>
        </div>
    </div>

</div>
<div class="container pt-5 ">
    <div class="text-center">


    </div><?php
 $result_alb = returnsongs($db, $row["albid"]);
 while ($rowsng = mysqli_fetch_array($result_alb, MYSQLI_ASSOC)) {
    require("./view/songCard.phtml");
}
?>
 </div>
</div>
</div>
<?php
require("./view/footer.phtml");
?>