<div class=" card my-4">
    <div class="card-body">
        <div class="container">
            <div class="row">

                <div class="col-md-2 d-inline" style="padding-left:0">
                <h5 class=" m-2" ><?php echo $comentar["usrnm"]?></h5>
                <h6 class=" m-2 text-muted"><?php echo $comentar["time"]; ?><h6>
                </div>
                <div class="col-md-8 d-inline">
                    <?php echo $comentar["comment"]; ?>
                </div>
                <div class="col-md-2 d-inline">
                    <?php
                     if (isset($_SESSION["user"])){
                        if ($_SESSION["user"]["id"] ==$comentar["usrid"] || $_SESSION["user"]["admin"] == 1 ){
                            echo "<a href='?deletecom={$comentar["cmid"]}' class=\"text-danger align-middle\">Delete</a>";
                        }
                        
                     }
                    
                    
                    ?>
                
                </div>
            </div>
        </div>
    </div>
</div>