<form action="addcomment.php" method="POST" autocomplete="off">
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label for="comment" class="col-form-label">Add comment</label>
        </div>
        <div class="col-auto">
        <textarea rows="4" cols="50" type="textarea" class="form-control" id="comment" name="comment" placeholder="Limit for your comment is 1024 chars" required="required" style="width: 900px;"></textarea>
            <input type="hidden" name="userid" value="<?php echo $_SESSION["user"]["id"] ?>">
            <input type="hidden" name="albid" value="<?php echo $row["albid"] ?>">
        </div>
        <div class="col-auto">
            <input type="submit" value="Comment">
        </div>
    </div>
</form>




