<form action="addcomment.php" method="POST" autocomplete="off">
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <label for="comment" class="col-form-label">Add comment</label>
        </div>
        <div class="col-auto">
            <input style="width:900px" type="text" id="comment" class="form-control" name="comment" required>
            <input type="hidden" name="userid" value="<?php echo $_SESSION["user"]["id"] ?>">
        </div>
        <div class="col-auto">
            <input type="submit" value="Comment">
        </div>
    </div>
</form>