<!doctype html>
<html lang="cs">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css">
  <link rel="icon" type="image/x-icon" href="Img/favicon.ico">
  <?php
  if (!isset($title)) {
    $title = "Rater";
  }

  ?>

  <link rel="stylesheet" href="css/style.css">
  <title><?php echo $title ?></title>
</head>

<body>

  <nav class="navbar navbar-expand-lg" style="position:absolute; background-color:var(--bs-black);width:100%;padding:10px; ;z-index: 20;">
    <a class="navbar-brand" href="index.php">
      <h1 style="color:#FFBB0D !important;">RATER</h1>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link mx-5 " href="browse.php" style="color:#FFBB0D !important;">Browse</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link mx-5 " href="find.php" style="color:#FFBB0D !important;">Find</a>
        </li>

        <li class="nav-item ">
          <a class="nav-link mx-5 " href="about.php" style="color:#FFBB0D !important;">About</a>
        </li>

      </ul>
      <?php
      if (isset($_SESSION["user"])) {
        echo '<h3 style="	font-weight: lighter;">' . $_SESSION["user"]["name"] . "</h3> ".'<button type="button" class=" mx-4 btn btn-primary"   onClick="location.href=\' logout.php \'" >   Logout  </button>';
      } else {
        echo '
    
    <div class=" my-2 my-lg-0">
    <button type="button" class=" mx-2 btn btn-secondary" onClick="location.href=\' login.php \'" >   Log In   </button>
    <button type="button" class=" mx-2 btn btn-primary"   onClick="location.href=\' signup.php \'" >   Sign Up  </button>
    ';
      }
      ?>
    </div>
    </div>
  </nav>