<style>
    .login-form {
        width: 340px;
        margin: auto;
    }

    .login-form form {
        margin-bottom: 15px;
        background-color: #333333;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }

    .login-form h2 {
        margin: 0 0 15px;
    }

    .form-control,
    .btn {
        min-height: 38px;
        border-radius: 2px;
    }

    .btn {
        font-size: 15px;
    }
footer{
    display: none !important;
}

</style>

<div class="login-form" style="padding-top:15%;">
    <form method="post">
        <h2 class="text-center">Log in</h2>
        <?php
        if (isset($chyba)){
            echo '<p class="text-center text-danger">'.$chyba.'<p>';

        }
       
        ?>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Email" required="required" name="email">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" required="required" name="password">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
        <div class="clearfix">
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>
    </form>
    <p class="text-center"><a href="signup.php">Create an Account</a></p>
</div>