<style>
    .login-form {
        width: 340px;
        margin: auto;
    }

    .login-form form {
        margin-bottom: 15px;
        background-color: #333333;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }

    .login-form h2 {
        margin: 0 0 15px;
    }

    .form-control,
    .btn {
        min-height: 38px;
        border-radius: 2px;
    }

    .btn {
        font-size: 15px;
    }
footer{
    display: none !important;
}

</style>


<div class="login-form" style="padding-top:15%;">
    <form method="post" class="pure-form">
        <h2 class="text-center">Sign up</h2>
       
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" required="required" name="username" maxlength = "32">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Email" required="required" name="email" maxlength = "64">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" id="password" required="required" name="password">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Confirm Password" id="confirm_password" required="required" name="password">
        </div>
        <h6 class="text-center text-muted font-weight-light">Please don't use your bank account password, I didn't spend much time on security.</h6>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block pure-button pure-button-primary">Sign up</button>
        </div>
        <span id='message'></span>
    </form>
    <p class="text-center"><a href="login.php">Already have an account? Log in.</a></p>
</div>

<script>
var password = document.getElementById("password")
  , confirm_password = document.getElementById("confirm_password");
function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}

password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;

</script>