<style>
    .login-form {
        width: 340px;
        margin: auto;
    }

    .login-form form {
        margin-bottom: 15px;
        background-color: #333333;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }

    .login-form h2 {
        margin: 0 0 15px;
    }

    .form-control,
    .btn {
        min-height: 38px;
        border-radius: 2px;
    }

    .btn {
        font-size: 15px;
    }
footer{
    display: none !important;
}

</style>

<div class="login-form" style="padding-top:15%;">
    <form method="post">
        <h2 class="text-center">Sign up</h2>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" required="required" name="username" maxlength = "32">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Email" required="required" name="email" maxlength = "64">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" required="required" name="password">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </div>

    </form>
    <p class="text-center"><a href="login.php">Already have an account? Log in.</a></p>
</div>